### ISSUE TITLE
I cant seem to find the Matte A øvinger

### ISSUE THREAD

**Issue by blauks** [Chaaarles/bookish-octo-invention#2]
I have looked through all the files, but I cant find any matte A øvinger. It might be a problem with nibble or the backend just broke, but I dont know. This is something that should be fixed ASAP. @Chaaarles

**Comment by Chaaarles** [comment]
Stop it right now >:O(

**Comment by blauks** [comment]
please, I really need this. My wife left me and there are only 3 more weeks of matte. I have only done one øving and my kids died, please consider doing this issue.

**Comment by Chaaarles** [comment]
> please, I really need this. My wife left me and there are only 3 more weeks of matte. I have only done one øving and my kids died, please consider doing this issue.

No

**Comment by Chaaarles** [comment]
@blauks Any progress on this?

**Comment by blauks** [comment]
Matte øvinger still gone 🤷‍♀️

**Comment by Chaaarles** [comment]
@blauks I see you closed this issue, but i still cannot find any Matte A øvinger?
If you could fix this it would be créme de la créme

**Comment by blauks** [comment]
no
